### ISSUE TITLE
With locally run Designer - unable to Export

### ISSUE THREAD

**Issue by vlcinsky** [mulesoft/api-designer#248]
When using Designer at anypoint, I am allowed to "Export Files".

When running it locally, I do not see any such option present.

Issue #95 explains, I can find the data in local storage in the browser, but having an option to export set of files into zip archive and import it into anypoint Designer makes testing of locally running services much easier.

**Comment by owianbarnett** [comment]
Great feature - Any ETA on master inclusion?
I am using it locally with the current master and find it extremely valuable with any more than a few files in the project that need to be fed into another tool like raml2html for regular republication.

**Comment by hanoii** [comment]
Even a plain file download would help a lot to start with.

**Comment by painbank** [comment]
+1

**Comment by jewelsjacobs** [comment]
+1 Update?

**Comment by jim-mclean** [comment]
This is the #1 reason why I can't recommend using RAML to my org.

**Comment by xaka** [comment]
Alright guys, I've finally managed to get it done and now even standalone API Designer supports exporting files as a ZIP archive. Please check out `master` branch and enjoy! :santa:

**Comment by jim-mclean** [comment]
Works great!  Thanks a bunch!!!

**Comment by usarid** [comment]
Good to hear! If you have a moment, I'd love to hear how you're getting value out of RAML, what's working and what's not, etc. uri at raml dot org






On Thu, May 14, 2015 at 5:01 AM -0700, "Jim Mclean" <notifications@github.com> wrote:












Works great!  Thanks a bunch!!!

**Comment by rezaloo** [comment]
Awesome work!

On Wednesday, May 13, 2015, Pavel Strashkin <notifications@github.com>
wrote:

> Alright guys, I've finally managed to get it done and now even standalone
> API Designer supports exporting files as a ZIP archive. Please check out
> master branch and enjoy! [image: :santa:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mulesoft/api-designer/issues/248#issuecomment-101877267>
> .
>


-- 
Sent from Gmail Mobile

**Comment by owianbarnett** [comment]
@usarid Uri,

RAML is great. Thank you et al for the wonderful work in this space. There are hurdles however I find myself working around either due to my limited understanding of the RAML feature set or due to limitations in it.

For example we are building up a library of API services with such different traits as, published services versus unpublished services. The later are simply services we want in the API but do not wish to include is the public distribution of the API documentation. I tried using traits but seems I cannot add a trait without content (ie. just a named trait). I want the RAML to document generator (I use RAML2HTML v1) to use the traits to generate the appropriate filtered outputs. I know we could have different RAML sources but that ain't pretty. For now I have added @internal (my concoction) into the description field and parse for these in my documentation templates.

In the same manner other extensible features would be handy to have to allow the RAML specification to embrace alternatives rather than restrict them.

Thanks again for RAML, it's a wonderful tool for defining APIs.

Ian.

**Comment by sichvoge** [comment]
Hi guys, this feature works brilliantly and therefore I am closing it as there is nothing else to do here. 

@owianbarnett could you raise your request on our forums at http://forums.raml.org/. Seems not related to this issue. Thank you :)
