### ISSUE TITLE
Console does not show me any type information inside the response section

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-designer#432]
Branch: develop
Milestone: v1

I defined a type inside a library and referenced to it inside  my response. I would expect the console to show me that information, but only get an empty panel:

![image](https://cloud.githubusercontent.com/assets/498114/18667932/8f71a888-7f2a-11e6-85b3-444c4696ee4b.png)

Weird thing. The information are shown inside the "Types" section inside the console.

![image](https://cloud.githubusercontent.com/assets/498114/18667950/a61e0a04-7f2a-11e6-8e84-9a4ac359a16d.png)

**Comment by sichvoge** [comment]
This is how it looks like in the current master version:

![image](https://cloud.githubusercontent.com/assets/498114/18668135/a0204cb0-7f2b-11e6-8dfb-fbd98572a1e6.png)

**Comment by sichvoge** [comment]
Might be related:

Using the following example:

```yaml
#%RAML 1.0
title: TestRAML
baseUri: http://someapi.com/api
mediaType: application/json

resourceTypes:
  collection:
    usage: Use this resourceType to represent a collection of <<resourcePathName|!singularize>> items
    description: A collection of <<resourcePathName>>
    get:
      description: |
        Get all <<resourcePathName>>,
        optionally filtered
      responses:
        200:
          body:
            type: <<typeName|!singularize>>[]

types:
  Member:
    properties:
      firstName: string
      lastName: string
      age: integer
    examples:
      Bob:
        value:
          firstName: "Bob"
          lastName: "Slidell"
          age: 42
      Bill:
        value:
          firstName: "Bill"
          lastName: "Lumberg"
          age: 41
/members:
  type:
     collection:
       typeName: <<resourcePathName|!uppercamelcase>>
  get:
```

I don't see anything in the console anymore:

![image](https://cloud.githubusercontent.com/assets/498114/18668348/cf373698-7f2c-11e6-987c-9e1fcd98c190.png)

That was working before.

**Comment by sichvoge** [comment]
OK with the last I do see something now but only the following:

![image](https://cloud.githubusercontent.com/assets/498114/18677429/9ef83fb2-7f50-11e6-8bed-dcc7abe85a04.png)

**Comment by sichvoge** [comment]
**UPDATE**

Using the current state, the informations are back for the initial problem:

![image](https://cloud.githubusercontent.com/assets/498114/18677563/0ae74074-7f51-11e6-93be-ccdbba4342f6.png)

Problems remain with the example in https://github.com/mulesoft/api-designer/issues/432#issuecomment-248273763

**Comment by javok002** [comment]
@sichvoge I tried out the example in the comment, and got this result:
![screen shot 2016-09-21 at 2 58 32 pm](https://cloud.githubusercontent.com/assets/5315281/18723097/b083defe-800d-11e6-8eaf-10182ef5d0f0.png)

This error happens when this syntax is used for the arrays:
` type: <<typeName|!singularize>>[]`
If instead it is written this way, it works:
` type: array
   items: <<typeName|!singularize>>`

The difference is in the JSON generated by the parser in the api-console. The first one generate this:
![screen shot 2016-09-21 at 3 19 42 pm](https://cloud.githubusercontent.com/assets/5315281/18723604/a1c12118-800f-11e6-9d2f-3d835a6bdebb.png)
While the second one expands the type right "items":
![screen shot 2016-09-21 at 3 19 22 pm](https://cloud.githubusercontent.com/assets/5315281/18723636/bcba6baa-800f-11e6-9101-983e620008b5.png)

We could change the generated JSON, expanding the type, in the api-designer. But maybe it is a better idea to fix this directly in the parser. What do you think about this?

**Comment by sichvoge** [comment]
That might be fixed with https://github.com/raml-org/raml-js-parser-2/issues/407. Hope that is going to be in the sprint release on Monday.
